from flask_pack import db
from flask_login import UserMixin
class User(db.Model,UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    password=db.Column(db.String(60), nullable=False)
    Designation = db.Column(db.String(20))
    Department_Working = db.Column(db.String(20))
    Reporting_Manager = db.Column(db.String(20))
    skills = db.Column(db.String(20))
    Avaiable_leaves= db.Column(db.String(20))
    Time  = db.Column(db.String(20))
    Leaves= db.Column(db.String(20))
    curtime= db.Column(db.String(20))
class emphour(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    JAN = db.Column(db.String(20))
    FEB = db.Column(db.String(20))
    MAR = db.Column(db.String(20))
    APR = db.Column(db.String(20))
    MAY = db.Column(db.String(20))
    JUN = db.Column(db.String(20))
    JUL = db.Column(db.String(20))
    AUG = db.Column(db.String(20))
    SEP = db.Column(db.String(20))
    OCT = db.Column(db.String(20))
    NOV = db.Column(db.String(20))
    DEC = db.Column(db.String(20))
class empholidays(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    JAN = db.Column(db.String(20))
    FEB = db.Column(db.String(20))
    MAR = db.Column(db.String(20))
    APR = db.Column(db.String(20))
    MAY = db.Column(db.String(20))
    JUN = db.Column(db.String(20))
    JUL = db.Column(db.String(20))
    AUG = db.Column(db.String(20))
    SEP = db.Column(db.String(20))
    OCT = db.Column(db.String(20))
    NOV = db.Column(db.String(20))
    DEC = db.Column(db.String(20))
class empholidays_reason(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    JAN = db.Column(db.String(20))
    FEB = db.Column(db.String(20))
    MAR = db.Column(db.String(20))
    APR = db.Column(db.String(20))
    MAY = db.Column(db.String(20))
    JUN = db.Column(db.String(20))
    JUL = db.Column(db.String(20))
    AUG = db.Column(db.String(20))
    SEP = db.Column(db.String(20))
    OCT = db.Column(db.String(20))
    NOV = db.Column(db.String(20))
    DEC = db.Column(db.String(20))
class emphour_m(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    JAN = db.Column(db.String(20))
    FEB = db.Column(db.String(20))
    MAR = db.Column(db.String(20))
    APR = db.Column(db.String(20))
    MAY = db.Column(db.String(20))
    JUN = db.Column(db.String(20))
    JUL = db.Column(db.String(20))
    AUG = db.Column(db.String(20))
    SEP = db.Column(db.String(20))
    OCT = db.Column(db.String(20))
    NOV = db.Column(db.String(20))
    DEC = db.Column(db.String(20))
    Department_Working = db.Column(db.String(20))